version: '3'

services:
  
  apache-pulsar:
    command: bin/pulsar standalone
    image: apachepulsar/pulsar-all
    container_name: apache-pulsar
    hostname: apache-pulsar
    volumes:
    - streaming-analytics:/pulsar/data
    ports:
    - 8080:8080
    - 6650:6650
    networks:
      - streaming-analytics
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8080/admin/v2/clusters/standalone

volumes:
  streaming-analytics:
    driver: local
    name: streaming-analytics

networks:
  streaming-analytics:
    driver: bridge
    name: streaming-analytics